version: '3.3'

volumes:
  postgres_data:
    driver: local

services:
  db:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: toDo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234